### ISSUE TITLE
Feature request(Provide README)

### ISSUE THREAD

**Issue by bigbigDreamer** [myNameIsDu/aktiv#21]
**Is your feature request related to a problem? Please describe.**
Should provide a completion README
**Describe the solution you'd like**
Help people to know the project.

**Describe alternatives you've considered**
[-] nothing
**Additional context**
[-]nothing

**Comment by myNameIsDu** [comment]
Yes, I will complete the document of launcher. As for the problem of the whole warehouse, I think it is a concluding thing, and it needs to wait until all functions are completed
